services:
  ##################################################
  nginx:
    image: nginx
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - type: volume
        source: wordpress-vol
        target: /var/www/html
    networks:
      - nginx-wordpress-net
    depends_on:
      - wordpress
    restart: always
  ##################################################
  wordpress:
    image: wordpress
    build: ./requirements/wordpress/
    container_name: wordpress
    ports:
      - 9000:9000
    volumes:
      - type: volume
        source: wordpress-vol
        target: /var/www/html
    environment:
      MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - nginx-wordpress-net
      - wordpress-mariadb-net
      - redis-wordpress-net
    depends_on:
      - mariadb
      - redis
    restart: always
  ##################################################
  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mariadb-vol
        target: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
    networks:
      - wordpress-mariadb-net
    restart: always
  ##################################################
  redis:
    image: redis
    build: ./requirements/bonus/redis/
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - redis-wordpress-net
    restart: always
  ##################################################
  ftp:
    image: ftp
    build: ./requirements/bonus/ftp/
    container_name: ftp
    ports:
      - 21:21
      - 4141-4242:4141-4242
    volumes:
      - type: volume
        source: wordpress-vol
        target: /var/www/html
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    restart: always
  ##################################################

volumes:
  ##################################################
  wordpress-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hhamza/data/wordpress
  ##################################################
  mariadb-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hhamza/data/mariadb
  ##################################################

networks:
  nginx-wordpress-net:
  wordpress-mariadb-net:
  redis-wordpress-net:
