services:
  ##################################################
  nginx:
    image: nginx
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - type: volume
        source: wordpress-vol
        target: /var/www/html
    networks:
      - nginx-wordpress-net
    depends_on:
      - wordpress
    restart: always
  ##################################################
  wordpress:
    image: wordpress
    build: ./requirements/wordpress/
    container_name: wordpress
    ports:
      - 9000:9000
    volumes:
      - type: volume
        source: wordpress-vol
        target: /var/www/html
    environment:
      MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    networks:
      - nginx-wordpress-net
      - wordpress-mariadb-net
    depends_on:
      - mariadb
    restart: always
  ##################################################
  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mariadb-vol
        target: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
    networks:
      - wordpress-mariadb-net
  ##################################################

volumes:
  ##################################################
  wordpress-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hhamza/data/wordpress
  ##################################################
  mariadb-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hhamza/data/mariadb
  ##################################################

networks:
  nginx-wordpress-net:
  wordpress-mariadb-net:
